server:
  port: 8100
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver 
    url: jdbc:mysql://localhost:3306/book-service?usertimezone=UTC&serverTimezone=UTC
    username: root
    password: neo@12345
  flyway:
    url: jdbc:mysql://localhost:3306/book-service?usertimezone=UTC&serverTimezone=UTC
    schemas:
      - book-service
    user: root
    password: neo@12345
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
  jpa:
   #hibernate:
      #ddl-auto: update
    show-sql: true
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5Dialect
  