server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  retry:
    instances:
      default: 
        maxAttempts: 5
        waitDuration: 2s
        enableRandomizedWait: true
        randomizedWaitFactor: 0.5
      default-2: 
        max-attempts: 10
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver 
    url: jdbc:mysql://localhost:3306/book-service?usertimezone=UTC&serverTimezone=UTC
    username: root
    password: neo@12345
  flyway:
    url: jdbc:mysql://localhost:3306/book-service?usertimezone=UTC&serverTimezone=UTC
    schemas:
      - book-service
    user: root
    password: neo@12345
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
  jpa:
   #hibernate:
      #ddl-auto: update
    show-sql: true
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5Dialect
  